### ISSUE TITLE
RememberMe Cookie Not Working

### ISSUE THREAD

**Issue by marco-wildermuth** [cron-eu/neos-playground#10]
This issue concerns the package https://github.com/cron-eu/neos-rememberme , which adds functionality for staying signed in (a.k.a. remember-me).
The problem is that cookies will not be set for the response in the authenticatedToken/loggedOut signal hooks, see https://github.com/cron-eu/neos-rememberme/blob/master/Classes/Package.php and https://github.com/cron-eu/neos-rememberme/blob/master/Classes/Neos/AuthenticationEventsHandler.php .

https://github.com/marco-wildermuth/neos-playground/tree/rememberme-showcase showcases this problem by using the Neos demo and Flowpack.Neos.FrontendLogin package.

# Setup
Clone https://github.com/marco-wildermuth/neos-playground/tree/rememberme-showcase (checkout the rememberme-showcase branch).
Follow the instructions in the [README.md](https://github.com/marco-wildermuth/neos-playground/blob/rememberme-showcase/README.md) to get the Neos Playground running.
Use `composer install` to get the packages locally.
Now overwrite the Login template from the CRON.RememberMeShowcase package to the Flowpack.Neos.FrontendLogin package:
`cp DistributionPackages/CRON.RememberMeShowcase/Resources/Private/Templates/Authentication/Index.html Packages/Plugins/Flowpack.Neos.FrontendLogin/Resources/Private/Templates/Authentication/Index.html`
(this includes the updated Login form and the remember-me checkbox)
or find out why the template overwrite doesn't work as described [here](https://github.com/Flowpack/Flowpack.Neos.FrontendLogin#rewriting-the-template-path-to-your-package) 🤬.

`make docker-sync`
`make dev-ssh`

Now import the slim demo content with the Login page:
`./flow site:import --package-key CRON.RememberMeShowcase`
and create a demo Frontend user:
```
./flow user:create \
  --username test@example.com \
  --password "password" \
  --first-name "Test" \
  --last-name "Example" \
  --authentication-provider "Flowpack.Neos.FrontendLogin:Frontend" \
  --roles "Flowpack.Neos.FrontendLogin:User"
```

# How To Test

Go to http://dev.neos-playground.docker:8081/en/login.html and log in with the credentials `test@example.com` and `password`, check the "Angemeldet bleiben" checkbox.

## Expectations
There should not be any cookie set except for the Neos_Session. The cookie `remember-me` is supposed to be set but is not.

## Debugging Results
The problem is probably that the wrong response is used to set the cookies.
Debugging using PHP's low level function `headers_sent()` showed that it is not the problem that the headers were already sent. `headers_list()` doesn't even list the cookie set via `$requestHandler->getHttpResponse()->setCookie(new Cookie(...))`.

See https://gist.github.com/bwaidelich/0932b015cfffd20ef40c919a78c439a8 for some sample code.

**Comment by marco-wildermuth** [comment]
@remuslazar @baschny This is the issue for the cookie problem.
I can't push branches to this repository, therefore I used my fork.

**Comment by baschny** [comment]
👍 good showcase, thanks @marco-wildermuth! @remuslazar you take a look at it, or else we could try to get outsider's help on that

**Comment by remuslazar** [comment]
@marco-wildermuth I was able to fix it, see https://github.com/cron-eu/neos-rememberme/pull/1
